#ifndef LIBLEDGER_BOLOS_APDU_
#define LIBLEDGER_BOLOS_APDU_

#define LEDGER_BOLOS_APDU_CLA 0xE0

#define LEDGER_BOLOS_APDU_INS_SECURE_INS         0x00
#define LEDGER_BOLOS_APDU_INS_GET_VERSION        0x01
#define LEDGER_BOLOS_APDU_INS_RESET              0x02
#define LEDGER_BOLOS_APDU_INS_VALIDATE_TARGET_ID 0x04
#define LEDGER_BOLOS_APDU_INS_ECHO               0xff

// Better naming?
#define LEDGER_BOLOS_APDU_INS_EXCHANGE_NONCE            0x50
#define LEDGER_BOLOS_APDU_INS_EXCHANGE_PUBLIC_KEY       0x51
#define LEDGER_BOLOS_APDU_INS_REQUEST_CERTIFICATE_CHAIN 0x52
#define LEDGER_BOLOS_APDU_INS_COMMIT_ECDH_CHANNEL       0x53

// Secure instructions, can only be used after a secure channel has been established (should be encrypted with the key)
#define LEDGER_BOLOS_APDU_SECINS_SELECT_SEGMENT 0x05
#define LEDGER_BOLOS_APDU_SECINS_LOAD_SEGMENT   0x06
#define LEDGER_BOLOS_APDU_SECINS_FLUSH_SEGMENT  0x07
#define LEDGER_BOLOS_APDU_SECINS_CRC_SEGMENT    0x08
#define LEDGER_BOLOS_APDU_SECINS_BOOT           0x09

// Speculation -> these codes aren't in the nonsecure-firmware git repo
#define LEDGER_BOLOS_APDU_SECINS_CREATE_APP       0x0B
#define LEDGER_BOLOS_APDU_SECINS_DELETE_APP       0x0C
#define LEDGER_BOLOS_APDU_SECINS_LIST_APP_RESTART 0x0E
#define LEDGER_BOLOS_APDU_SECINS_LIST_APP         0x0F
#define LEDGER_BOLOS_APDU_SECINS_SETUP_CUSTOM_CA  0x12
#define LEDGER_BOLOS_APDU_SECINS_RESET_CUSTOM_CA  0x13
#define LEDGER_BOLOS_APDU_SECINS_RUN_APP          0x14

#endif /* LIBLEDGER_BOLOS_APDU_ */
