#ifndef LIBLEDGER_BOLOS_CONSTANTS_H_
#define LIBLEDGER_BOLOS_CONSTANTS_H_

#define LEDGER_BOLOS_APDU_CLA 0xE0

#define LEDGER_BOLOS_APDU_INS_SECURE   0x00
#define LEDGER_BOLOS_APDU_INS_VERSION  0x01
#define LEDGER_BOLOS_APDU_INS_RESET    0x02
#define LEDGER_BOLOS_APDU_INS_VALIDATE 0x04

#define LEDGER_BOLOS_APDU_INS_NONCE          0x50
#define LEDGER_BOLOS_APDU_INS_PUBLICKEY      0x51
#define LEDGER_BOLOS_APDU_INS_CERTIFICATE    0x52
#define LEDGER_BOLOS_APDU_INS_COMMIT_CHANNEL 0x53

#endif /* LIBLEDGER_BOLOS_CONSTANTS_H_ */
