#ifndef LIBLEDGER_BITCOIN_APDU_H_
#define LIBLEDGER_BITCOIN_APDU_H_

#ifdef __cplusplus
extern "C" {
#endif

#define LEDGER_APDU_CLA     0xE0
#define LEDGER_APDU_ADM_CLA 0xD0

#define LEDGER_APDU_INS_SETUP                    0x20
#define LEDGER_APDU_VERIFY_PIN                   0x22
#define LEDGER_APDU_INS_GET_OPERATION_MODE       0x24
#define LEDGER_APDU_INS_SET_OPERATION_MODE       0x26
#define LEDGER_APDU_INS_SET_KEYMAP               0x28
#define LEDGER_APDU_INS_SET_COMM_PROTOCOL        0x2A
#define LEDGER_APDU_INS_GET_WALLET_PUBLIC_KEY    0x40
#define LEDGER_APDU_INS_GET_TRUSTED_INPUT        0x42
#define LEDGER_APDU_INS_HASH_INPUT_START         0x44
#define LEDGER_APDU_INS_HASH_INPUT_FINALIZE      0x46
#define LEDGER_APDU_INS_HASH_SIGN                0x48
#define LEDGER_APDU_INS_HASH_INPUT_FINALIZE_FULL 0x4A
#define LEDGER_APDU_INS_GET_INTERNAL_CHAIN_INDEX 0x4C
#define LEDGER_APDU_INS_SIGN_MESSAGE             0x4E
#define LEDGER_APDU_INS_GET_TRANSACTION_LIMIT    0xA0
#define LEDGER_APDU_INS_SET_TRANSACTION_LIMIT    0xA2
#define LEDGER_APDU_INS_IMPORT_PRIVATE_KEY       0xB0
#define LEDGER_APDU_INS_GET_PUBLIC_KEY           0xB2
#define LEDGER_APDU_INS_DERIVE_BIP32_KEY         0xB4
#define LEDGER_APDU_INS_SIGNVERIFY_IMMEDIATE     0xB6
#define LEDGER_APDU_INS_GET_RANDOM               0xC0
#define LEDGER_APDU_INS_GET_ATTESTATION          0xC2
#define LEDGER_APDU_INS_GET_FIRMWARE_VERSION     0xC4
#define LEDGER_APDU_INS_COMPOSE_MOFN_ADDRESS     0xC6
#define LEDGER_APDU_INS_DONGLE_AUTHENTICATE      0xC8
#define LEDGER_APDU_INS_GET_POS_SEED             0xCA

#define LEDGER_APDU_INS_ADM_INIT_KEYS            0x20
#define LEDGER_APDU_INS_ADM_INIT_ATTESTATION     0x22
#define LEDGER_APDU_INS_ADM_GET_UPDATE_ID        0x24
#define LEDGER_APDU_INS_ADM_FIRMWARE_UPDATE      0x42

#ifdef __cplusplus
}
#endif

#endif /* LIBLEDGER_BITCOIN_APDU_H_ */